name: Deploy to Railway

on:
  push:
    branches:
      - main # Sesuaikan dengan branch Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }} # Tambahkan DATABASE_URL ke environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node 20
        uses: actions/setup-node@v3 # Gunakan setup-node versi terbaru
        with:
          node-version: 20.16.0

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies
        run: npm install

      - name: Create .env.production file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.production
          echo "NODE_ENV=production" >> .env.production
          echo "IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }}" >> .env.production
          echo "IMAGEKIT_SECRET_KEY=${{ secrets.IMAGEKIT_SECRET_KEY }}" >> .env.production
          echo "IMAGEKIT_URL_ENDPOINT=${{ secrets.IMAGEKIT_URL_ENDPOINT }}" >> .env.production

      - name: Deploy to Railway
        run: |
          railway up --service test-deploy-a

      - name: Setup database
        run: railway run --service test-deploy-a npx prisma migrate deploy --env-file .env.production
