name: Deploy to Railway

on:
  push:
    branches:
      - main # Pastikan ini sesuai dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
      IMAGEKIT_SECRET_KEY: ${{ secrets.IMAGEKIT_SECRET_KEY }}
      IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Install dependencies
        run: npm install

      - name: Debug Environment Variables
        run: |
          echo "IMAGEKIT_PUBLIC_KEY: $IMAGEKIT_PUBLIC_KEY"
          echo "IMAGEKIT_SECRET_KEY: $IMAGEKIT_SECRET_KEY"
          echo "IMAGEKIT_URL_ENDPOINT: $IMAGEKIT_URL_ENDPOINT"

      - name: Deploy to Railway
        run: |
          railway up --service harmonious-benevolence

      - name: Setup database
        run: npx prisma migrate deploy

      - name: Start Application
        run: npm start
